--Q1. What is the total revenue generated by male vs. female customers? 

SELECT gender, SUM(purchase_amount) AS Total_Revenue
FROM customer
GROUP BY gender;
--SELECT * FROM customer;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount)
      FROM customer
  );

--Q3. Which are the top 5 products with the highest average review rating?
  SELECT 
    item_purchased,
    round(AVG(review_rating:: numeric),2) AS average_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_review_rating DESC
LIMIT 5;

SELECT shipping_type, FROM customer


-- Q4. Compare the average purchase amounts between 
-- Standard and Express Shipping. 

SELECT shipping_type, round(Avg(purchase_amount),2) FROM customer
where shipping_type in ('Standard','Express')
group by shipping_type



-- Q5. Do subscribed customers spend more? 
-- Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
	count(customer_id) as total_customer,
    round(AVG(purchase_amount),2) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;




-- Q6. Which 5 products have the highest percentage of 
-- purchases with discounts applied?
SELECT
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;






-- Q7. Segment customers into New, Returning, and Loyal based on their 
-- total number of previous purchases, and show the count of each segment. 

SELECT
    customer_segment,
    COUNT(*) AS customer_count
FROM (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) AS segmented_customers
GROUP BY customer_segment
ORDER BY customer_count DESC;




-- Q8. What are the top 3 most purchased products within each category? 

WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer
    GROUP BY category, item_purchased
),
ranked_products AS (
    SELECT
        category,
        item_purchased,
        purchase_count,
        Row_number() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS product_rank
    FROM product_counts
)
SELECT
    category,
    item_purchased,
    purchase_count,
    product_rank
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category, product_rank, item_purchased;





-- Q9. Are customers who are repeat buyers—more than 5 previous purchases—
-- also more likely to subscribe?
SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;




-- Q10. What is the revenue contribution of each age group? 


SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
